export const fleetData = [
  // City Car (Ekonomis)
  {
    name: "Honda Brio",
    image: "/armada/brio.webp",
    category: "city",
    maticPrice: "Rp 350.000",
    manualPrice: "Rp 300.000",
    year: "2023",
    fuel: "Bensin",
    seats: "5",
    features: "AC, Audio",
  },
  {
    name: "Daihatsu Ayla",
    image: "/armada/ayla.webp",
    category: "city",
    maticPrice: "Rp 350.000",
    manualPrice: "Rp 300.000",
    year: "2023",
    fuel: "Bensin",
    seats: "5",
    features: "AC, Audio",
  },
  {
    name: "Toyota Agya",
    image: "/armada/agya.webp",
    category: "city",
    maticPrice: "Rp 350.000",
    manualPrice: "Rp 300.000",
    year: "2023",
    fuel: "Bensin",
    seats: "5",
    features: "AC, Audio",
  },
  {
    name: "Toyota Calya",
    image: "/armada/calya.webp",
    category: "city",
    maticPrice: "Rp 350.000",
    manualPrice: "Rp 300.000",
    year: "2023",
    fuel: "Bensin",
    seats: "7",
    features: "AC, Audio",
  },
  {
    name: "Daihatsu Sigra",
    image: "/armada/sigra.webp",
    category: "city",
    maticPrice: "Rp 350.000",
    manualPrice: "Rp 300.000",
    year: "2023",
    fuel: "Bensin",
    seats: "7",
    features: "AC, Audio",
  },

  // MPV Keluarga
  {
    name: "Toyota Avanza/Xenia",
    image: "/armada/avanza.webp",
    category: "mpv",
    maticPrice: "Rp 350.000",
    manualPrice: "Rp 300.000",
    year: "2023",
    fuel: "Bensin",
    seats: "7",
    features: "AC, Audio",
  },
  {
    name: "All New Avanza",
    image: "/armada/avanza.webp",
    category: "mpv",
    maticPrice: "Rp 450.000",
    manualPrice: "Rp 400.000",
    year: "2023",
    fuel: "Bensin",
    seats: "7",
    features: "Safety Sense",
  },
  {
    name: "Suzuki Ertiga",
    image: "/armada/suzuki-ertiga.webp",
    category: "mpv",
    maticPrice: "Rp 450.000",
    manualPrice: "Rp 400.000",
    year: "2023",
    fuel: "Bensin",
    seats: "7",
    features: "AC, Audio",
  },
  {
    name: "Mitsubishi Xpander",
    image: "/armada/xpander.webp",
    category: "mpv",
    maticPrice: "Rp 450.000",
    manualPrice: "Rp 400.000",
    year: "2023",
    fuel: "Bensin",
    seats: "7",
    features: "Touchscreen",
  },

  // SUV Compact
  {
    name: "Suzuki XL7",
    image: "/armada/suzuki-xl-7.webp",
    category: "suv",
    maticPrice: "Rp 450.000",
    manualPrice: "Rp 400.000",
    year: "2023",
    fuel: "Bensin",
    seats: "7",
    features: "Premium Audio",
  },
  {
    name: "Daihatsu Terios",
    image: "/armada/terios.webp",
    category: "suv",
    maticPrice: "Rp 450.000",
    manualPrice: "Rp 400.000",
    year: "2023",
    fuel: "Bensin",
    seats: "7",
    features: "AC, 4x2",
  },
  {
    name: "Toyota Rush",
    image: "/armada/toyota-rush.webp",
    category: "suv",
    maticPrice: "Rp 450.000",
    manualPrice: "Rp 400.000",
    year: "2023",
    fuel: "Bensin",
    seats: "7",
    features: "Touchscreen",
  },

  // Executive MPV
  {
    name: "Grand Innova Diesel",
    image: "/armada/innova-reborn.webp",
    category: "executive",
    maticPrice: "Rp 450.000",
    manualPrice: "Rp 400.000",
    year: "2023",
    fuel: "Diesel",
    seats: "8",
    features: "Premium Interior",
  },
  {
    name: "Innova Reborn",
    image: "/armada/innova-reborn.webp",
    category: "executive",
    maticPrice: "Rp 600.000",
    manualPrice: "Rp 550.000",
    year: "2023",
    fuel: "Bensin",
    seats: "8",
    features: "Captain Seat",
  },
  {
    name: "Innova Zenix",
    image: "/armada/innova-reborn.webp",
    category: "executive",
    maticPrice: "Rp 750.000",
    manualPrice: null,
    year: "2023",
    fuel: "Bensin Hybrid",
    seats: "8",
    features: "Premium Features",
  },

  // Premium SUV
  {
    name: "Toyota Fortuner",
    image: "/armada/fortuner.webp",
    category: "premium",
    allInPrice: "Rp 1.300.000",
    lepasKunci: "Hubungi Kami",
    year: "2023",
    fuel: "Bensin",
    seats: "7",
    features: "4x4, Luxury Interior",
  },
  {
    name: "Mitsubishi Pajero Sport",
    image: "/armada/pajero.webp",
    category: "premium",
    allInPrice: "Rp 1.300.000",
    lepasKunci: "Hubungi Kami",
    year: "2023",
    fuel: "Diesel",
    seats: "7",
    features: "4x4, Premium Features",
  },

  // Luxury & Commercial
  {
    name: "Toyota Alphard",
    image: "/armada/toyota-alphard.webp",
    category: "luxury",
    allInPrice: "Rp 2.400.000",
    lepasKunci: "Hubungi Kami",
    year: "2023",
    fuel: "Diesel",
    seats: "8",
    features: "Executive Lounge",
  },
  {
    name: "Hiace Commuter",
    image: "/armada/hiace-commuter.webp",
    category: "luxury",
    allInPrice: "Rp 1.300.000",
    lepasKunci: "Hubungi Kami",
    year: "2023",
    fuel: "Diesel",
    seats: "15",
    features: "AC, Comfortable",
  },
  {
    name: "Hiace Premio",
    image: "/armada/hiace-premio.webp",
    category: "luxury",
    allInPrice: "Rp 1.500.000",
    lepasKunci: "Hubungi Kami",
    year: "2023",
    fuel: "Diesel",
    seats: "15",
    features: "Premium Interior",
  },
  {
    name: "Hiace Premio Luxury",
    image: "/armada/hiace-premio-luxury.webp",
    category: "luxury",
    allInPrice: "Rp 2.500.000",
    lepasKunci: "Hubungi Kami",
    year: "2023",
    fuel: "Diesel",
    seats: "15",
    features: "Full Luxury Features",
  },
  {
    name: "Isuzu Elf Minibus",
    image: "/armada/isuzu-elf-minibus.webp",
    category: "luxury",
    allInPrice: "Rp 1.400.000",
    lepasKunci: "Hubungi Kami",
    year: "2023",
    fuel: "Diesel",
    seats: "20",
    features: "Commercial Use",
  },
  {
    name: "Hilux Double Cabin",
    image: "/armada/hilux-double-cabin.webp",
    category: "luxury",
    allInPrice: "Rp 1.600.000",
    lepasKunci: "Hubungi Kami",
    year: "2023",
    fuel: "Diesel",
    seats: "5",
    features: "Pickup Truck",
  },
]
